apiVersion: v1
kind: Namespace
metadata:
  name: "demo"

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-static-pod
  namespace: "demo"
spec:
  containers:
    - name: nginx
      image: "nginx"
      ports:
        - name: "web"
          hostPort: 8080
          protocol: "TCP"
          containerPort: 80